/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ExtensionCard: typeof import('./src/components/ExtensionCard.vue')['default']
    FeatureCard: typeof import('./src/components/FeatureCard.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
  }
}
